# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# android/fastlane/Fastfile

default_platform(:android)

platform :android do
 desc "Deploy to Firebase"
 lane :deploy_android do
  begin
    gradle(
        task: 'assemble',
        build_type: 'Release'
      )
    firebase_app_distribution(
          groups: "flutter-team",
          release_notes: "Bug fixes and improvements.",
          apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
          app: "1:1026635662194:android:5c5c40f4cda07841b613eb",
    )
  end
 end
end